import type { Property, User } from "./types"

export const mockUsers: User[] = [
  {
    id: "user1",
    name: "Administrador",
    email: "admin@propiedades.com",
    role: "admin",
    avatar: "/professional-woman-diverse.png",
    phone: "+34 600 000 001",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "user2",
    name: "Agente Inmobiliario",
    email: "agente@propiedades.com",
    role: "agent",
    avatar: "/professional-man.png",
    phone: "+34 600 000 002",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "user3",
    name: "Cliente Premium",
    email: "cliente@email.com",
    role: "client",
    phone: "+34 600 000 003",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
]

export const mockProperties: Property[] = [
  {
    id: "1",
    title: "Casa Moderna en Zona Residencial",
    description:
      "Hermosa casa de dos plantas con acabados de lujo, jardín amplio y ubicación privilegiada en zona residencial exclusiva.",
    price: 450000,
    location: {
      address: "Calle Los Robles 123",
      city: "Madrid",
      state: "Madrid",
      zipCode: "28001",
      coordinates: { lat: 40.4168, lng: -3.7038 },
    },
    details: {
      bedrooms: 4,
      bathrooms: 3,
      area: 280,
      yearBuilt: 2020,
      propertyType: "house",
      status: "available",
    },
    images: ["/modern-house-exterior.png", "/modern-living-room.png", "/modern-kitchen.png", "/modern-bedroom.png"],
    features: ["Jardín", "Garaje", "Piscina", "Aire acondicionado", "Calefacción", "Seguridad 24h"],
    agent: {
      id: "agent1",
      name: "María González",
      email: "maria@propiedades.com",
      phone: "+34 600 123 456",
      avatar: "/professional-woman-diverse.png",
    },
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "2",
    title: "Apartamento Céntrico con Vistas",
    description:
      "Elegante apartamento en el centro de la ciudad con vistas panorámicas y todas las comodidades modernas.",
    price: 320000,
    location: {
      address: "Avenida Gran Vía 45",
      city: "Madrid",
      state: "Madrid",
      zipCode: "28013",
      coordinates: { lat: 40.42, lng: -3.7025 },
    },
    details: {
      bedrooms: 2,
      bathrooms: 2,
      area: 120,
      yearBuilt: 2018,
      propertyType: "apartment",
      status: "available",
    },
    images: [
      "/modern-apartment-exterior.png",
      "/apartment-city-view.png",
      "/modern-apartment-kitchen.png",
      "/cozy-apartment-bedroom.png",
    ],
    features: ["Ascensor", "Balcón", "Aire acondicionado", "Portero", "Trastero"],
    agent: {
      id: "agent2",
      name: "Carlos Ruiz",
      email: "carlos@propiedades.com",
      phone: "+34 600 789 012",
      avatar: "/professional-man.png",
    },
    createdAt: "2024-01-10T14:30:00Z",
    updatedAt: "2024-01-10T14:30:00Z",
  },
  {
    id: "3",
    title: "Chalet con Piscina y Jardín",
    description:
      "Espectacular chalet independiente con amplio jardín, piscina privada y múltiples espacios de entretenimiento.",
    price: 680000,
    location: {
      address: "Urbanización Las Colinas 78",
      city: "Pozuelo de Alarcón",
      state: "Madrid",
      zipCode: "28223",
      coordinates: { lat: 40.4378, lng: -3.8122 },
    },
    details: {
      bedrooms: 5,
      bathrooms: 4,
      area: 420,
      yearBuilt: 2019,
      propertyType: "house",
      status: "available",
    },
    images: [
      "/luxury-villa-pool.png",
      "/luxury-living-room.png",
      "/luxury-kitchen-island.png",
      "/luxurious-master-suite.png",
    ],
    features: ["Piscina", "Jardín", "Garaje doble", "Bodega", "Gimnasio", "Barbacoa", "Seguridad"],
    agent: {
      id: "agent1",
      name: "María González",
      email: "maria@propiedades.com",
      phone: "+34 600 123 456",
      avatar: "/professional-woman-diverse.png",
    },
    createdAt: "2024-01-05T09:15:00Z",
    updatedAt: "2024-01-05T09:15:00Z",
  },
  {
    id: "4",
    title: "Loft Industrial Renovado",
    description: "Único loft de estilo industrial completamente renovado, con techos altos y diseño contemporáneo.",
    price: 280000,
    location: {
      address: "Calle Industria 12",
      city: "Barcelona",
      state: "Cataluña",
      zipCode: "08025",
      coordinates: { lat: 41.3851, lng: 2.1734 },
    },
    details: {
      bedrooms: 1,
      bathrooms: 1,
      area: 95,
      yearBuilt: 1980,
      propertyType: "apartment",
      status: "pending",
    },
    images: ["/industrial-loft-exterior.png", "/industrial-loft.png", "/loft-kitchen.png", "/loft-bedroom.png"],
    features: ["Techos altos", "Vigas vistas", "Suelos originales", "Terraza", "Ascensor"],
    agent: {
      id: "agent3",
      name: "Ana Martín",
      email: "ana@propiedades.com",
      phone: "+34 600 345 678",
      avatar: "/professional-woman-agent.png",
    },
    createdAt: "2024-01-08T16:45:00Z",
    updatedAt: "2024-01-12T11:20:00Z",
  },
  {
    id: "5",
    title: "Dúplex con Terraza Panorámica",
    description: "Impresionante dúplex en última planta con terraza de 60m² y vistas espectaculares de la ciudad.",
    price: 520000,
    location: {
      address: "Torre Skyline, Piso 15",
      city: "Valencia",
      state: "Valencia",
      zipCode: "46001",
      coordinates: { lat: 39.4699, lng: -0.3763 },
    },
    details: {
      bedrooms: 3,
      bathrooms: 2,
      area: 180,
      yearBuilt: 2021,
      propertyType: "apartment",
      status: "available",
    },
    images: [
      "/penthouse-terrace-city-view.png",
      "/duplex-living-room.png",
      "/modern-duplex-kitchen.png",
      "/duplex-master-bedroom.png",
    ],
    features: ["Terraza", "Vistas panorámicas", "Ascensor", "Parking", "Trastero", "Aire acondicionado"],
    agent: {
      id: "agent2",
      name: "Carlos Ruiz",
      email: "carlos@propiedades.com",
      phone: "+34 600 789 012",
      avatar: "/professional-man.png",
    },
    createdAt: "2024-01-12T12:00:00Z",
    updatedAt: "2024-01-12T12:00:00Z",
  },
  {
    id: "6",
    title: "Casa Rural con Finca",
    description:
      "Encantadora casa rural con 2 hectáreas de terreno, perfecta para desconectar y disfrutar de la naturaleza.",
    price: 380000,
    location: {
      address: "Camino del Valle s/n",
      city: "Segovia",
      state: "Castilla y León",
      zipCode: "40001",
      coordinates: { lat: 40.9429, lng: -4.1088 },
    },
    details: {
      bedrooms: 4,
      bathrooms: 2,
      area: 200,
      yearBuilt: 1995,
      propertyType: "house",
      status: "available",
    },
    images: ["/rural-house-countryside.png", "/rustic-fireplace.png", "/country-kitchen.png", "/rural-bedroom.png"],
    features: ["Finca", "Chimenea", "Pozo", "Huerto", "Barbacoa", "Garaje"],
    agent: {
      id: "agent3",
      name: "Ana Martín",
      email: "ana@propiedades.com",
      phone: "+34 600 345 678",
      avatar: "/professional-woman-agent.png",
    },
    createdAt: "2024-01-03T08:30:00Z",
    updatedAt: "2024-01-03T08:30:00Z",
  },
]
